"""Add Maintenance table

Revision ID: 3bea2eb53515
Revises: 
Create Date: 2025-01-29 09:01:49.480894

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3bea2eb53515'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_id'), 'maintenance', ['id'], unique=False)
    op.drop_index('idx_properties_available', table_name='properties')
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.drop_index('idx_tenants_email', table_name='tenants')
    op.drop_index('idx_tenants_phone', table_name='tenants')
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.create_index('idx_tenants_phone', 'tenants', ['phone'], unique=False)
    op.create_index('idx_tenants_email', 'tenants', ['email'], unique=False)
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.create_index('idx_properties_available', 'properties', ['available'], unique=False)
    op.drop_index(op.f('ix_maintenance_id'), table_name='maintenance')
    op.drop_table('maintenance')
    # ### end Alembic commands ###
