"""Add a Field in the property table

Revision ID: aef66722eb90
Revises: 3bea2eb53515
Create Date: 2025-01-29 09:55:19.198081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef66722eb90'
down_revision: Union[str, None] = '3bea2eb53515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'tenant_id')
    # ### end Alembic commands ###
